# Generated by Django 4.1.1 on 2023-01-12 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Surname")),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "summary",
                    models.TextField(
                        help_text="Short lesson description",
                        max_length=1000,
                        verbose_name="Description",
                    ),
                ),
                # ("isbn", models.CharField(max_length=13, verbose_name="ISBN")),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="yoga.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Entry type description",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique lesson code",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "due_back",
                    models.DateField(
                        blank=True, null=True, verbose_name="Will be available"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ('p', 'Planning'),
                            ('a', 'Not available'),
                            ('b', 'Book'),
                            ('r', 'Reserved'),
                        ],
                        default="p",
                        help_text="Status",
                        max_length=1,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="yoga.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["due_back"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="type",
            field=models.ManyToManyField(
                help_text="Entry lesson title", to="yoga.type"
            ),
        ),
    ]
