# Generated by Django 4.1.1 on 2023-01-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yoga", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",

            options={"verbose_name": "Lesson", "verbose_name_plural": "Lessons"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Type", "verbose_name_plural": "Types"},
        ),
        migrations.AddField(
            model_name="teacher",
            name="description",
            field=models.TextField(
                default="bio", max_length=2000, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="yoga.teacher",
            ),
        ),
    ]
