# Generated by Django 4.1.1 on 2023-01-20 14:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('yoga', '0004_lessoninstance_student_alter_lesson_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
