# Generated by Django 4.1.1 on 2023-01-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_alter_teacher_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.ManyToManyField(help_text='Please choose type of this lesson', to='yoga.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Entry lesson title', max_length=200, verbose_name='Title'),
        ),
    ]
