# Generated by Django 4.1.1 on 2023-01-23 21:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_alter_lesson_type_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninstance',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Planning'), ('a', 'Not available'), ('b', 'You can book'), ('r', 'Reserved')], default='p', help_text='Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=tinymce.models.HTMLField(default='cia turi buti pamokos aprasymas'),
        ),
    ]
