# Generated by Django 4.1.1 on 2023-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0007_alter_lessoninstance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Price'),
        ),
    ]
