# Generated by Django 4.1.1 on 2023-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0008_lesson_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis')),
            ],
        ),
    ]
