# Generated by Django 4.1.1 on 2023-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(help_text='Short lesson description', max_length=1000, verbose_name='Description'),
        ),
    ]
