# Generated by Django 4.1.1 on 2023-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yoga', '0011_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(help_text='Short description', max_length=1000, verbose_name='Description'),
        ),
    ]
