# Generated by Django 4.1.1 on 2023-01-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0012_remove_gallery_content_alter_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='type',
            new_name='lesson_type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='Short description', max_length=1000, verbose_name='Description'),
        ),
    ]
